version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run: 
        - name: Install dependencies
        - command: pip install SpeechRecognitio openai pyttsx3
      - run:
        - name: run test
        - command: python -m pytest
